# ui/pages.py

PAGES = ["STATUS", "CONFIG", "HEALTH", "MODE"]
PAGE_STATUS = 0
PAGE_CONFIG = 1
PAGE_HEALTH = 2
PAGE_MODE   = 3

STATUS_SUBPAGES = ["STATE", "INPUT", "BATTERY"]
SUB_STATE  = 0
SUB_INPUT  = 1
SUB_BATTERY= 2
